---
abstract: 'install (nearly) all modules by MARCEL'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  Test::Compile: 0
  Test::More: 0.70
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bundle-MARCEL
no_index:
  directory:
    - inc
    - t
recommends:
  Test::Pod: 0
  Test::Pod::Coverage: 0
requires:
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
